controller:
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    hostname: jenkins.3.67.0.140.nip.io
  installPlugin:
  - kubernetes:1.22.6
  - workflow-aggregator:2.6
  - git 4.7.1
  - configuration-as-code:1-as-code:1.51
  - blueocean:1.24.6
